[tool.poetry]
name = "ai_researcher"
version = "0.1.0"
description = "AI Researcher Demo"
authors = ["Markus Ecker <markus.ecker@gmail.com>"]
license = "MIT"

[project]
name = "ai_researcher"
version = "0.0.1"
dependencies = [
  "langgraph",
  "langchain_core",
  "langchain_openai",
  "langchain",
  "openai",
  "langchain-community",
  "tavily-python",
  "copilotkit",
]

[build-system]
requires = ["setuptools >= 61.0"]
build-backend = "setuptools.build_meta"

[tool.poetry.dependencies]
python = "^3.12"
langgraph = "^0.2.14"
langchain-core = "^0.2.36"
langchain-openai = "^0.1.23"
langchain = "^0.2.15"
openai = "^1.43.0"
langchain-community = "^0.2.14"
tavily-python = "^0.4.0"
copilotkit = "0.1.16"

[tool.poetry.scripts]
demo = "ai_researcher.demo:main"
