blank_issues_enabled: true
contact_links:
  - name: ğŸ§‘â€ğŸ“ Documentation
    url: https://docs.copilot.ai
    about: Read the documentation to get started.
  - name: ğŸ‘¾ Discord
    url: https://discord.com/invite/6dffbvGU3D
    about: Join the Discord server to ask questions and get help.