apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.app.name }}-outputs
data:
  app.name: {{ .Values.app.name }}
  deployments: |
    [
      {{- $root := . }}
      {{- range $deploymentIndex, $deployment := .Values.deployments }}
        {
          "deployment": "{{ $deployment.name }}",
          "url": "https://{{ $root.Values.app.name }}-{{ $deployment.name }}-{{ $root.Values.environment}}.demos.devcopilotkit.com",
          {{- if $deployment.outputs }}
          "outputs": {{ $deployment.outputs | toJson }}
          {{- else }}
          "outputs": {}
          {{- end }}
        }{{- if ne $deploymentIndex (sub (len $root.Values.deployments) 1) }}, {{- end }}
      {{- end }}
    ]