[project]
name = "research_canvas"
version = "0.0.1"
description = "Research Canvas"
authors = [
    { name = "Markus Ecker", email = "markus.ecker@gmail.com" }
]
license = { text = "MIT" }
requires-python = ">=3.12,<3.13"
dependencies = [
    "copilotkit>=0.1.74",
    "langchain-openai>=1.1.6",
    "langchain-community>=0.4.1",
    "langchain-anthropic>=1.3.0",
    "langchain-google-genai>=2.0.5",
    "langchain>=0.3.4",
    "openai>=1.52.1",
    "tavily-python>=0.5.0",
    "python-dotenv>=1.0.1",
    "uvicorn>=0.31.0",
    "requests>=2.32.3",
    "html2text>=2024.2.26",
    "langchain-core>=0.3.25",
    "langgraph-cli[inmem]>=0.4.11",
    "langgraph-checkpoint-sqlite>=3.0.1",
    "aiosqlite>=0.20.0",
    "aiohttp>=3.9.3",
    "langgraph>=1.0.5"
]
