name: Preview Environments (Destroy)

on:
  pull_request:
    types: [ closed ]

jobs:
  preview_envs_destroy:
    if: contains(github.event.pull_request.labels.*.name, 'preview')
    runs-on: ubuntu-latest
    name: Destroy Preview Environments
    permissions:
      deployments: write
      pull-requests: write
      statuses: write
      actions: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - uses: pnpm/action-setup@v4
        with:
          version: 9
          
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Auth AWS CDK Public Registry
        run: |
          aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws

      - uses: dopplerhq/secrets-fetch-action@v1.2.0
        id: doppler
        with:
          doppler-token: ${{ secrets.DOPPLER_TOKEN }}
          doppler-project: copilotkit-previews
          doppler-config: prd

      - name: Infra install dependencies
        working-directory: infra
        run: pnpm i

      - name: cdk destroy
        uses: youyo/aws-cdk-github-actions@v2
        with:
          working_dir: './infra'
          cdk_subcommand: 'destroy'
          cdk_args: '--force'
          actions_comment: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_PR_NUMBER: ${{ github.event.number }}
          OPENAI_API_KEY: ${{ steps.doppler.outputs.OPENAI_API_KEY }}

      - name: Comment post-destroy
        uses: thollander/actions-comment-pull-request@v3
        with:
          comment-tag: preview-status-update
          message: |
            Preview environments destroyed for this pull request.